# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2b1df8a3bcdc699b30f1bfc7e477a5f18895f92818636e4e7b2e6769e031c80cd999d9286f976e1b0931529127108546f54c43dbcdb92576af3d80b8875ce4b

test:
  secret_key_base: ae4fc231d4367d1045adfad670b800533963730afe4681a7fc7dda39b67f1f75698e9ad08abcb513a88cce596b59b5bbbfc7dcb0b748caa893a80bbf96e3861a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
