# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 064c315e0ad5334f9350d45f6f34a23df90143d0162298edbf9012d3852524f79e74627ea986656158e1680590c02bf32eb707f800aebb5e6a68359c46ec9098

test:
  secret_key_base: a1b91a1772ca30723de3f7ade0c07b03e80f50682fbba57d33a8fc31e65409d1e7cc3772f721fb6d76e277e26b86652fcb189bf3512424a4433f6e2a5fa12ead

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
